# Generated by Django 4.2.6 on 2024-01-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_shop_customer_name_remove_shop_mobile_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
